### ISSUE TITLE
still alive

### ISSUE THREAD

**Issue by titoasty** [SnpM/Lockstep-Framework#124]
Hi,

I'm very interested in using this framework (I already worked on lockstep networking & physics).
So is the project still alive ? Do you need any help ?
Thanks

**Comment by nibsbin** [comment]
Hello,

I've been busy with Christmas vacation and now study. I work on LSF when I
can. There's a fog of war feature coming soon ;)

Regards,

John

**Comment by titoasty** [comment]
Nice !
And any news about the documentation ?
I can't wait beginning using it ! :)

**Comment by nibsbin** [comment]
Sorry for the long time titoasty D:

Instead of disappearing and leaving people hanging, I wrote [something](https://github.com/SnpM/LockstepFramework/issues/125) to describe my situation and why I haven't been very active developing LS.

I realize that documentation is very important and I regret not working on it from day 1.

In the following weeks, I will either make LS what I always dreamed it should be or officially stop development.

**Comment by bianchengxiaobei** [comment]
Why AABox_AABox not support?

**Comment by nibsbin** [comment]
Polygons and Axis-aligned boxes are, at the moment, static objects for
boundaries, buildings, etc. so they don't interact with each other. I do
think that making them dynamic physics objects would add a lot of
flexibility. I will try to tackle this in the future.

On Tue, Oct 10, 2017 at 11:48 PM, bianchengxiaobei <notifications@github.com
