### ISSUE TITLE
Agent Scan Always Have GC Alloc

### ISSUE THREAD

**Issue by zikerlin** [SnpM/Lockstep-Framework#133]
![gc alloc](https://user-images.githubusercontent.com/6878979/33202477-aa2ef422-d137-11e7-85c9-36659fd43f9e.png)

Scan->BehaveWithTarget

**Comment by nibsbin** [comment]
Hey Zikerlin, thanks for the heads up. I can't easily reproduce this. How many units are you simulating?

**Comment by zikerlin** [comment]
Hi John Pan, I use 400 units to simulating.

2017-11-24 23:21 GMT+08:00 John Pan <notifications@github.com>:

**Comment by nibsbin** [comment]
Ah, sorry for the late response. Busy with life and stuff.

400 units is a decent number of units. If they're all clumped up in the same place, a lot of calls will be made to search for targets to attack. Also deep profiler adds a minor hit on each method called since it's logging in a stopwatch. From those statistics though, Lockstep Framework should run with no significant performance issues.
