### ISSUE TITLE
Use arrays or FastCollections 

### ISSUE THREAD

**Issue by WenmingChan** [SnpM/Lockstep-Framework#163]
I wonder to know why there are many Arrays used,For example,LSAgent[] in AgentController.cs and Ability[] in AbilityManager.cs.And why not use FastCollections instead. when should I use FastCollections or arrays?

**Comment by nibsbin** [comment]
Hey Wenming,

FastCollections use arrays internally. They're faster than List, Hashset,
etc. in certain situations because they have less safety checks and have
functions that skip garbage collection and iteration (e.g. FastClear).

LS uses FastCollections to significantly speed up high-volume processes
like pathfinding.

Sometimes it's easier or faster to just use arrays.

**Comment by WenmingChan** [comment]
Thank you!
