### ISSUE TITLE
Hi，when will support AABox/Poly collide?

### ISSUE THREAD

**Issue by devilmaywork** [SnpM/Lockstep-Framework#168]
It will be very useful，thank you。。

**Comment by nibsbin** [comment]
AABox-Poly and Poly-Poly collision will be pretty involved to implement. The biggest limiting factor is rotation. Lockstep Framework physics isn't a realistic physics engine; it's currently designed for masses of units to keep them from occupying the same location. Basic velocity and momentum are implemented but torque isn't considered at all. This is no problem for circle objects because their collision behavior isn't affected by rotation as much as a polygon (e.g. circle rotating vs baseball bat rotating).

At the moment, AABox and Polygon-shaped colliders are intended for environment only; they don't get pushed around by collision resolution. Implementing collision between these shapes would require hacking in torque and a true momentum system. This would be useful for deterministic 2D physics-based games but out of the scope of RTS/TD/MOBA.
